upstream:
  externalResolvers:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - https://dns10.quad9.net/dns-query
blocking:
  blockType: nxDomain
  blackLists:
    ads:
      - https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
      - https://adaway.org/hosts.txt
      - https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&showintro=1&mimetype=plaintext
      - https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt
      - https://raw.githubusercontent.com/durablenapkin/scamblocklist/master/adguard.txt
      - https://raw.githubusercontent.com/hant0508/uBlock-filters/master/filters.txt
      - https://filters.adtidy.org/extension/ublock/filters/2.txt
      - https://easylist-downloads.adblockplus.org/cntblock.txt
      - https://easylist-downloads.adblockplus.org/advblock.txt
      - https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV-AGH.txt
      - https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_3_Spyware/filter.txt
      - https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_17_TrackParam/filter.txt
      - https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_4_Social/filter.txt
      - https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_1_Russian/filter.txt
      - https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_11_Mobile/filter.txt
      - https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_15_DnsFilter/filter.txt
      - https://raw.githubusercontent.com/xxcriticxx/.pl-host-file/master/hosts.txt
      - https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/Subscribable-Lists/CountryCodesLists/Russia.txt
      - https://raw.githubusercontent.com/TakoYachty/Gift-Card-Killer/master/Mega%20Untrusted%20Hosts%20Blocker.txt
  clientGroupsBlock:
    default:
      - ads
port: 53
httpPort: 80